[package]
name = "cw32-gen"
version = "0.24.0"
edition = "2021"
rust-version = "1.99"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
serde={version="=1.0.229",features=["derive"]}
serde_yaml="=0.9.34-deprecated"
serde_json="=1.0.151"
chiptool = { git = "https://github.com/embassy-rs/chiptool", rev = "be1bff3e9e1b27b090e69bd9ac753c66fdcce678" }
proc-macro2 = "=1.0.107"
quote = "=1.0.47"
syn = { version = "=2.0.106", features = ["full", "visit-mut", "extra-traits"] }
prettyplease = "=0.2.37"
