//! Blocking GPIO subset. Alternate-function/EXTI/DMA support is not implemented.
use crate::{pac, Peri, PeripheralType};
use core::convert::Infallible;
use embedded_hal::digital::{ErrorType, InputPin, OutputPin, StatefulOutputPin};

// Port identities, addresses, enable bits and capabilities are generated.
include!(concat!(env!("OUT_DIR"), "/_generated_gpio.rs"));
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Level {
    Low,
    High,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Pull {
    None,
    Up,
}

/// Copyable GPIO identity. Only an exclusive `Peri<AnyPin>` authorizes a driver.
/// Prefer die-level singleton tokens generated by HAL build.rs; verify board bonding.
/// The unsafe constructor is only for extending the audited pin set.
#[derive(Clone, Copy)]
pub struct AnyPin {
    port: Port,
    number: u8,
}
impl AnyPin {
    /// # Safety
    /// The pin must be bonded on the exact package, exclusively owned, and not
    /// used by debug, oscillators, or any other peripheral. GPIO constructors select AF0 and overwrite its GPIO configuration.
    /// Calling this twice for one pin, or accessing it through another PAC/HAL,
    /// violates the ownership contract. Do not use PA13/PA14 (SWD) by default.
    pub unsafe fn steal(port: Port, number: u8) -> Peri<'static, Self> {
        unsafe { Peri::new_unchecked(Self::new(port, number)) }
    }
    pub(crate) fn new(port: Port, number: u8) -> Self {
        assert!(number < 16, "GPIO number must be in 0..16");
        assert!(
            port.implemented_mask() & (1u16 << number) != 0,
            "GPIO does not exist on this die"
        );
        Self { port, number }
    }
    fn mask(&self) -> u32 {
        1u32 << self.number
    }
    fn addr(&self, offset: usize) -> usize {
        self.port.base() + offset
    }
    unsafe fn setup(&self) {
        unsafe {
            #[cfg(sysctrl_l012)]
            pac::modify(
                pac::SYSCTRL_BASE + pac::sysctrl::AHBEN,
                pac::SYSCTRL_KEY_MASK,
                pac::SYSCTRL_KEY | self.port.clock_bit(),
            );
            #[cfg(sysctrl_f030)]
            pac::modify(
                pac::SYSCTRL_BASE + pac::sysctrl::AHBEN,
                0,
                self.port.clock_bit(),
            );
            // Disable output before changing mux; AFRH precedes AFRL on CW32.
            pac::modify(self.addr(pac::gpio::DIR), 0, self.mask());
            let af = if u32::from(self.number) < pac::gpio::PINS_PER_AFR {
                pac::gpio::AFRL
            } else {
                pac::gpio::AFRH
            };
            let shift = (u32::from(self.number) % pac::gpio::PINS_PER_AFR) * pac::gpio::AF_BITS;
            let field_mask = ((1u32 << pac::gpio::AF_BITS) - 1) << shift;
            pac::modify(self.addr(af), field_mask, pac::gpio::AF_GPIO << shift);
            pac::modify(self.addr(pac::gpio::RISEIE), self.mask(), 0);
            pac::modify(self.addr(pac::gpio::FALLIE), self.mask(), 0);
            #[cfg(gpio_f030)]
            {
                pac::modify(self.addr(pac::gpio::HIGHIE), self.mask(), 0);
                pac::modify(self.addr(pac::gpio::LOWIE), self.mask(), 0);
            }
            pac::modify(self.addr(pac::gpio::ANALOG), self.mask(), 0);
            // L012 implements only PF03 pull-down; F030 implements all port pins.
            // The metadata mask prevents writing unimplemented bits on either IP.
            if self.port.pulldown_mask() & (1u16 << self.number) != 0 {
                pac::modify(self.addr(pac::gpio::PDR), self.mask(), 0);
            }
        }
    }
}

pub struct Output<'d> {
    pin: Peri<'d, AnyPin>,
}
impl<'d> Output<'d> {
    pub fn new(pin: Peri<'d, impl Pin>, initial: Level) -> Self {
        let pin = pin.into();
        critical_section::with(|_| unsafe {
            pin.setup();
            pac::modify(pin.addr(pac::gpio::PUR), pin.mask(), 0);
            pac::modify(pin.addr(pac::gpio::OPENDRAIN), pin.mask(), 0);
            // Preload output latch BEFORE enabling output direction.
            pac::write(
                pin.addr(if initial == Level::High {
                    pac::gpio::BSRR
                } else {
                    pac::gpio::BRR
                }),
                pin.mask(),
            );
            pac::modify(pin.addr(pac::gpio::DIR), pin.mask(), 0);
        });
        Self { pin }
    }
    pub fn set_level(&mut self, level: Level) {
        unsafe {
            pac::write(
                self.pin.addr(if level == Level::High {
                    pac::gpio::BSRR
                } else {
                    pac::gpio::BRR
                }),
                self.pin.mask(),
            );
        }
    }
    pub fn toggle(&mut self) {
        unsafe {
            pac::write(self.pin.addr(pac::gpio::TOG), self.pin.mask());
        }
    }
    pub fn release(self) -> Peri<'d, AnyPin> {
        self.pin
    }
}
impl ErrorType for Output<'_> {
    type Error = Infallible;
}
impl OutputPin for Output<'_> {
    fn set_low(&mut self) -> Result<(), Self::Error> {
        self.set_level(Level::Low);
        Ok(())
    }
    fn set_high(&mut self) -> Result<(), Self::Error> {
        self.set_level(Level::High);
        Ok(())
    }
}
impl StatefulOutputPin for Output<'_> {
    fn is_set_high(&mut self) -> Result<bool, Self::Error> {
        Ok(unsafe { pac::read(self.pin.addr(pac::gpio::ODR)) } & self.pin.mask() != 0)
    }
    fn is_set_low(&mut self) -> Result<bool, Self::Error> {
        self.is_set_high().map(|x| !x)
    }
    fn toggle(&mut self) -> Result<(), Self::Error> {
        Output::toggle(self);
        Ok(())
    }
}

pub struct Input<'d> {
    pin: Peri<'d, AnyPin>,
}
impl<'d> Input<'d> {
    pub fn new(pin: Peri<'d, impl Pin>, pull: Pull) -> Self {
        let pin = pin.into();
        critical_section::with(|_| unsafe {
            pin.setup();
            pac::modify(pin.addr(pac::gpio::DIR), 0, pin.mask());
            pac::modify(
                pin.addr(pac::gpio::PUR),
                pin.mask(),
                if pull == Pull::Up { pin.mask() } else { 0 },
            );
        });
        Self { pin }
    }
    pub fn release(self) -> Peri<'d, AnyPin> {
        self.pin
    }
}
impl ErrorType for Input<'_> {
    type Error = Infallible;
}
impl InputPin for Input<'_> {
    fn is_high(&mut self) -> Result<bool, Self::Error> {
        Ok(unsafe { pac::read(self.pin.addr(pac::gpio::IDR)) } & self.pin.mask() != 0)
    }
    fn is_low(&mut self) -> Result<bool, Self::Error> {
        self.is_high().map(|x| !x)
    }
}

impl AnyPin {
    /// Internal mux operation, called only after a generated signal trait proves a route.
    pub(crate) fn configure_alternate(&self, af: u8, output: bool) {
        assert!(u32::from(af) < (1 << pac::gpio::AF_BITS));
        critical_section::with(|_| unsafe {
            self.setup();
            pac::modify(self.addr(pac::gpio::PUR), self.mask(), 0);
            pac::modify(self.addr(pac::gpio::OPENDRAIN), self.mask(), 0);
            let reg = if u32::from(self.number) < pac::gpio::PINS_PER_AFR {
                pac::gpio::AFRL
            } else {
                pac::gpio::AFRH
            };
            let shift = (u32::from(self.number) % pac::gpio::PINS_PER_AFR) * pac::gpio::AF_BITS;
            let mask = ((1 << pac::gpio::AF_BITS) - 1) << shift;
            pac::modify(self.addr(reg), mask, u32::from(af) << shift);
            if output {
                pac::modify(self.addr(pac::gpio::DIR), self.mask(), 0);
            }
        });
    }
    pub(crate) fn configure_analog(&self) {
        critical_section::with(|_| unsafe {
            self.setup();
            pac::modify(self.addr(pac::gpio::PUR), self.mask(), 0);
            pac::modify(self.addr(pac::gpio::ANALOG), 0, self.mask());
        });
    }
    /// Return an owned pin to high-impedance digital input and GPIO mux.
    pub(crate) fn disconnect(&self) {
        critical_section::with(|_| unsafe {
            self.setup();
            pac::modify(self.addr(pac::gpio::PUR), self.mask(), 0);
        });
    }
}

/// Sealed pin identities. Identity values alone never authorize MMIO.
pub(crate) mod sealed {
    pub trait Pin {}
}
pub trait Pin: sealed::Pin + PeripheralType + Into<AnyPin> {}
impl PeripheralType for AnyPin {}
impl sealed::Pin for AnyPin {}
impl Pin for AnyPin {}
