//! GPIO drivers using Embassy's owned/borrowed pin and flexible-driver model.
//!
//! CW32L012 has no programmable output speed; speed arguments and `Speed` are
//! available only on CW32F030. Pull-down is checked against each pin's actual
//! capability. Dropping a driver returns its pin to floating digital input,
//! preserving the output latch and shared port clock.
use crate::{pac, Peri, PeripheralType};
use core::convert::Infallible;
use embedded_hal::digital::{ErrorType, InputPin, OutputPin, StatefulOutputPin};

// Port identities, addresses, enable bits and capabilities are generated.
include!(concat!(env!("OUT_DIR"), "/_generated_gpio.rs"));

/// Digital input or output level.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Level {
    Low,
    High,
}
impl From<bool> for Level {
    fn from(value: bool) -> Self {
        if value {
            Self::High
        } else {
            Self::Low
        }
    }
}
impl From<Level> for bool {
    fn from(value: Level) -> Self {
        value == Level::High
    }
}

/// Internal weak pull resistor selection.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Pull {
    None,
    Up,
    /// Only pins in the generated pull-down capability mask support this.
    /// On CW32L012 this is PF03; other pins reject it before register access.
    Down,
}

/// CW32F030 output slew rate (GPIO.SPEED), not drive strength.
///
/// Only the two hardware encodings are exposed. The achievable frequency
/// depends on load and supply voltage; see the chip's electrical specifications.
/// Encodings: CW32x030 reference manual Rev 2.5, section 9.6.3.
#[cfg(gpio_f030)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Speed {
    /// SPEED.PINy = 0.
    Low,
    /// SPEED.PINy = 1.
    High,
}

/// CW32F030 output drive strength (GPIO.DRIVER), independent of slew rate.
///
/// Mode changes preserve this setting. Only an explicit call to
/// `set_drive_strength` changes it.
/// Encodings: CW32x030 reference manual Rev 2.5, section 9.6.9.
#[cfg(gpio_f030)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum DriveStrength {
    /// DRIVER.PINy = 1.
    Low,
    /// DRIVER.PINy = 0 (the hardware reset setting).
    High,
}

/// GPIO output type.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum OutputType {
    PushPull,
    OpenDrain,
}

/// Alternate-function pin settings. The direction is explicit on CW32.
#[derive(Clone, Copy, Debug)]
pub struct AfType {
    output: bool,
    output_type: OutputType,
    pull: Pull,
    #[cfg(gpio_f030)]
    speed: Speed,
}
impl AfType {
    pub const fn input(pull: Pull) -> Self {
        Self {
            output: false,
            output_type: OutputType::PushPull,
            pull,
            #[cfg(gpio_f030)]
            speed: Speed::Low,
        }
    }
    pub const fn output(output_type: OutputType, #[cfg(gpio_f030)] speed: Speed) -> Self {
        Self::output_pull(
            output_type,
            #[cfg(gpio_f030)]
            speed,
            Pull::None,
        )
    }
    pub const fn output_pull(
        output_type: OutputType,
        #[cfg(gpio_f030)] speed: Speed,
        pull: Pull,
    ) -> Self {
        Self {
            output: true,
            output_type,
            pull,
            #[cfg(gpio_f030)]
            speed,
        }
    }
}

/// GPIO pin number, or an encoded port-and-pin identity.
pub type PinNumber = u8;

/// Copyable GPIO identity. Only an exclusive `Peri<AnyPin>` authorizes a driver.
/// Prefer die-level singleton tokens generated by HAL build.rs; verify bonding.
#[derive(Clone, Copy, Debug)]
pub struct AnyPin {
    port: Port,
    number: PinNumber,
}
impl AnyPin {
    /// Construct an owned pin from `port_number * 16 + pin_number`.
    /// Port A is 0, B is 1, C is 2, and F is 5.
    ///
    /// # Safety
    /// The pin must be bonded on the exact package, exclusively owned, and not
    /// used by debug, oscillators, or another peripheral. Constructors select
    /// AF0 and overwrite its GPIO configuration. Creating overlapping handles
    /// or accessing it through another PAC/HAL violates exclusive ownership.
    /// Do not repurpose PA13/PA14 (SWD) by default.
    pub const unsafe fn steal(pin_port: PinNumber) -> Peri<'static, Self> {
        let port = match Port::from_number(pin_port / 16) {
            Some(port) => port,
            None => panic!("GPIO port does not exist on this die"),
        };
        unsafe { Peri::new_unchecked(Self::new(port, pin_port % 16)) }
    }
    pub(crate) const fn new(port: Port, number: PinNumber) -> Self {
        assert!(number < 16, "GPIO number must be in 0..16");
        assert!(
            port.implemented_mask() & (1u16 << number) != 0,
            "GPIO does not exist on this die"
        );
        Self { port, number }
    }
    fn regs(&self) -> pac::gpio::Gpio {
        // The generated port metadata supplies this chip's peripheral address.
        // Generic port access intentionally carries no instance reset default.
        unsafe { pac::gpio::Gpio::from_ptr(self.port.base() as *mut ()) }
    }
    /// Raw register block. The caller must coordinate access with HAL drivers.
    #[cfg(feature = "unstable-pac")]
    pub fn block(&self) -> pac::gpio::Gpio {
        self.regs()
    }
    fn validate_pull(&self, pull: Pull) {
        assert!(
            pull != Pull::Down || self.port.pulldown_mask() & (1u16 << self.number) != 0,
            "this GPIO pin has no internal pull-down"
        );
    }
    // The caller owns the pin and holds the shared-port critical section.
    fn setup(&self) {
        self.port.enable_clock();
        let gpio = self.regs();
        let n = usize::from(self.number);
        // Stop driving before changing the mux or any electrical configuration.
        gpio.dir().modify(|w| w.set_pin(n, true));
        // Logical bank 0 is AFRL at +0x18, bank 1 is AFRH at +0x14 on CW32.
        gpio.afr(n / 8).modify(|w| w.set_afr(n % 8, 0));
        gpio.riseie().modify(|w| w.set_pin(n, false));
        gpio.fallie().modify(|w| w.set_pin(n, false));
        #[cfg(gpio_f030)]
        {
            gpio.highie().modify(|w| w.set_pin(n, false));
            gpio.lowie().modify(|w| w.set_pin(n, false));
        }
        gpio.analog().modify(|w| w.set_pin(n, false));
        self.set_pull(Pull::None);
        gpio.opendrain().modify(|w| w.set_pin(n, false));
    }
    // Call only after validate_pull and while holding the critical section.
    fn set_pull(&self, pull: Pull) {
        let gpio = self.regs();
        let n = usize::from(self.number);
        // Disable both pulls first, so an Up <-> Down transition never enables
        // both resistors. Do not access unimplemented L012 pull-down bits.
        gpio.pur().modify(|w| w.set_pin(n, false));
        if self.port.pulldown_mask() & (1u16 << self.number) != 0 {
            #[cfg(gpio_l012)]
            gpio.pdr().modify(|w| w.set_pin3(false));
            #[cfg(gpio_f030)]
            gpio.pdr().modify(|w| w.set_pin(n, false));
        }
        match pull {
            Pull::None => {}
            Pull::Up => gpio.pur().modify(|w| w.set_pin(n, true)),
            Pull::Down => {
                #[cfg(gpio_l012)]
                gpio.pdr().modify(|w| w.set_pin3(true));
                #[cfg(gpio_f030)]
                gpio.pdr().modify(|w| w.set_pin(n, true));
            }
        }
    }
    #[cfg(gpio_f030)]
    fn set_speed(&self, speed: Speed) {
        // CW32F030 RM 9.6.3: SPEED 0 = low, 1 = high. DRIVER is independent.
        self.regs()
            .speed()
            .modify(|w| w.set_pin(usize::from(self.number), speed == Speed::High));
    }
    fn set_level(&self, level: Level) {
        let gpio = self.regs();
        let n = usize::from(self.number);
        match level {
            Level::High => gpio.bsrr().write(|w| w.set_bss(n, true)),
            Level::Low => gpio.brr().write(|w| w.set_brr(n, true)),
        }
    }
    fn set_as_af(&self, af: u8, af_type: AfType) {
        assert!(u32::from(af) < (1 << pac::gpio::AF_BITS));
        self.validate_pull(af_type.pull);
        critical_section::with(|_| {
            self.setup();
            let gpio = self.regs();
            let n = usize::from(self.number);
            self.set_pull(af_type.pull);
            gpio.opendrain()
                .modify(|w| w.set_pin(n, af_type.output_type == OutputType::OpenDrain));
            #[cfg(gpio_f030)]
            self.set_speed(af_type.speed);
            gpio.afr(n / 8).modify(|w| w.set_afr(n % 8, af));
            if af_type.output {
                gpio.dir().modify(|w| w.set_pin(n, false));
            }
        });
    }
    /// Internal mux operation after a generated signal trait proves the route.
    /// Preserve electrical speed/drive settings chosen by the owning driver.
    pub(crate) fn configure_alternate(&self, af: u8, output: bool) {
        assert!(u32::from(af) < (1 << pac::gpio::AF_BITS));
        critical_section::with(|_| {
            self.setup();
            let gpio = self.regs();
            let n = usize::from(self.number);
            gpio.afr(n / 8).modify(|w| w.set_afr(n % 8, af));
            if output {
                gpio.dir().modify(|w| w.set_pin(n, false));
            }
        });
    }
    pub(crate) fn configure_analog(&self) {
        critical_section::with(|_| {
            self.setup();
            self.regs()
                .analog()
                .modify(|w| w.set_pin(usize::from(self.number), true));
        });
    }
    /// Return to floating digital input with AF0; keep the output latch intact.
    pub(crate) fn disconnect(&self) {
        critical_section::with(|_| self.setup());
    }
}
impl core::fmt::Display for AnyPin {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(
            f,
            "P{}{}",
            char::from(b'A' + self.port.number()),
            self.number
        )
    }
}
#[cfg(feature = "defmt")]
impl defmt::Format for AnyPin {
    fn format(&self, f: defmt::Formatter) {
        defmt::write!(
            f,
            "P{}{}",
            char::from(b'A' + self.port.number()),
            self.number
        );
    }
}

/// GPIO flexible pin, sharing one implementation for all digital driver modes.
///
/// The output latch is remembered across input, analog, and disconnected modes.
/// Its initial value is unspecified; preload it before enabling output.
#[derive(Debug)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct Flex<'d> {
    pub(crate) pin: Peri<'d, AnyPin>,
}
impl<'d> Flex<'d> {
    /// Acquire the pin, enable its port clock, and leave it floating.
    /// Unlike STM32's global initialization, CW32 establishes this per pin.
    pub fn new(pin: Peri<'d, impl Pin>) -> Self {
        let pin: Peri<'d, AnyPin> = pin.into();
        pin.disconnect();
        Self { pin }
    }
    /// Duplicate this driver without enforcing exclusive ownership.
    ///
    /// # Safety
    /// Only one copy may access or reconfigure the pin at a time, including Drop.
    pub const unsafe fn clone_unchecked(&self) -> Self {
        Self {
            pin: unsafe { self.pin.clone_unchecked() },
        }
    }
    /// Configure a digital input with the requested weak pull.
    ///
    /// # Panics
    /// Panics before register access if this pin has no requested pull-down.
    pub fn set_as_input(&mut self, pull: Pull) {
        self.pin.validate_pull(pull);
        critical_section::with(|_| {
            self.pin.setup();
            self.pin.set_pull(pull);
        });
    }
    /// Configure push-pull output using the existing output latch.
    /// Set its level first if a particular initial value is required.
    pub fn set_as_output(&mut self, #[cfg(gpio_f030)] speed: Speed) {
        self.configure_output(
            OutputType::PushPull,
            #[cfg(gpio_f030)]
            speed,
            Pull::None,
        );
    }
    /// Configure open-drain output and digital input, without weak pulls.
    /// A high output latch releases the line; a low latch drives it low.
    pub fn set_as_input_output(&mut self, #[cfg(gpio_f030)] speed: Speed) {
        self.set_as_input_output_pull(
            #[cfg(gpio_f030)]
            speed,
            Pull::None,
        );
    }
    /// Configure open-drain output and digital input with a weak pull.
    ///
    /// # Panics
    /// Panics before register access if this pin has no requested pull-down.
    pub fn set_as_input_output_pull(&mut self, #[cfg(gpio_f030)] speed: Speed, pull: Pull) {
        self.configure_output(
            OutputType::OpenDrain,
            #[cfg(gpio_f030)]
            speed,
            pull,
        );
    }
    fn configure_output(
        &mut self,
        output_type: OutputType,
        #[cfg(gpio_f030)] speed: Speed,
        pull: Pull,
    ) {
        self.pin.validate_pull(pull);
        critical_section::with(|_| {
            self.pin.setup();
            self.pin.set_pull(pull);
            let gpio = self.pin.regs();
            let n = usize::from(self.pin.number);
            gpio.opendrain()
                .modify(|w| w.set_pin(n, output_type == OutputType::OpenDrain));
            #[cfg(gpio_f030)]
            self.pin.set_speed(speed);
            // All configuration is complete and the caller's latch is intact.
            gpio.dir().modify(|w| w.set_pin(n, false));
        });
    }
    /// Configure analog input, disabling digital output and weak pulls.
    pub fn set_as_analog(&mut self) {
        self.pin.configure_analog();
    }
    /// Disconnect the pin as floating digital input, without clearing its latch.
    pub fn set_as_disconnected(&mut self) {
        self.pin.disconnect();
    }
    /// Select an alternate function without checking a peripheral signal route.
    /// This does not acquire the peripheral or verify board wiring. Prefer the
    /// owning peripheral driver's generated signal traits whenever possible.
    pub fn set_as_af_unchecked(&mut self, af_num: u8, af_type: AfType) {
        self.pin.set_as_af(af_num, af_type);
    }
    /// Set CW32F030's independent output drive-strength bit.
    #[cfg(gpio_f030)]
    pub fn set_drive_strength(&mut self, strength: DriveStrength) {
        critical_section::with(|_| {
            self.pin.regs().driver().modify(|w| {
                w.set_pin(usize::from(self.pin.number), strength == DriveStrength::Low)
            });
        });
    }
    pub fn is_high(&self) -> bool {
        self.pin
            .regs()
            .idr()
            .read()
            .pin(usize::from(self.pin.number))
    }
    pub fn is_low(&self) -> bool {
        !self.is_high()
    }
    pub fn level(&self) -> Level {
        self.is_high().into()
    }
    pub fn is_set_high(&self) -> bool {
        self.pin
            .regs()
            .odr()
            .read()
            .pin(usize::from(self.pin.number))
    }
    pub fn is_set_low(&self) -> bool {
        !self.is_set_high()
    }
    pub fn output_level(&self) -> Level {
        self.is_set_high().into()
    }
    pub fn set_high(&mut self) {
        self.set_level(Level::High);
    }
    pub fn set_low(&mut self) {
        self.set_level(Level::Low);
    }
    pub fn set_level(&mut self, level: Level) {
        self.pin.set_level(level);
    }
    pub fn toggle(&mut self) {
        self.pin
            .regs()
            .tog()
            .write(|w| w.set_pin(usize::from(self.pin.number), true));
    }
    /// Transfer the exclusive, type-erased token without changing the hardware.
    ///
    /// This intentionally bypasses Drop's disconnect: the current mode and
    /// output latch are preserved, as in the original CW32 `release` API.
    pub fn release(self) -> Peri<'d, AnyPin> {
        let this = core::mem::ManuallyDrop::new(self);
        // SAFETY: Drop has been suppressed and the sole token is moved out once.
        unsafe { core::ptr::read(&this.pin) }
    }
}
impl Drop for Flex<'_> {
    fn drop(&mut self) {
        self.pin.disconnect();
    }
}

/// GPIO digital input. Dropping it disconnects the pin.
pub struct Input<'d> {
    pub(crate) pin: Flex<'d>,
}
impl<'d> Input<'d> {
    /// Acquire and configure the pin. Unsupported pull-downs panic before MMIO.
    pub fn new(pin: Peri<'d, impl Pin>, pull: Pull) -> Self {
        let pin: Peri<'d, AnyPin> = pin.into();
        pin.validate_pull(pull);
        let mut pin = Flex::new(pin);
        pin.set_as_input(pull);
        Self { pin }
    }
    /// Wrap an existing Flex without reconfiguring it. Configure input first.
    pub const fn from_flex(pin: Flex<'d>) -> Self {
        Self { pin }
    }
    pub fn is_high(&self) -> bool {
        self.pin.is_high()
    }
    pub fn is_low(&self) -> bool {
        self.pin.is_low()
    }
    pub fn level(&self) -> Level {
        self.pin.level()
    }
    /// Transfer ownership without changing the pin's mode or output latch.
    /// Unlike ordinary Drop, this does not disconnect the pin.
    pub fn release(self) -> Peri<'d, AnyPin> {
        self.pin.release()
    }
}

/// GPIO push-pull output. Dropping it disconnects the pin.
pub struct Output<'d> {
    pub(crate) pin: Flex<'d>,
}
impl<'d> Output<'d> {
    pub fn new(
        pin: Peri<'d, impl Pin>,
        initial_output: Level,
        #[cfg(gpio_f030)] speed: Speed,
    ) -> Self {
        let mut pin = Flex::new(pin);
        // Flex starts as input, so the latch is loaded before output is enabled.
        pin.set_level(initial_output);
        pin.set_as_output(
            #[cfg(gpio_f030)]
            speed,
        );
        Self { pin }
    }
    pub fn set_high(&mut self) {
        self.pin.set_high();
    }
    pub fn set_low(&mut self) {
        self.pin.set_low();
    }
    pub fn set_level(&mut self, level: Level) {
        self.pin.set_level(level);
    }
    pub fn is_set_high(&self) -> bool {
        self.pin.is_set_high()
    }
    pub fn is_set_low(&self) -> bool {
        self.pin.is_set_low()
    }
    pub fn output_level(&self) -> Level {
        self.pin.output_level()
    }
    pub fn toggle(&mut self) {
        self.pin.toggle();
    }
    #[cfg(gpio_f030)]
    pub fn set_drive_strength(&mut self, strength: DriveStrength) {
        self.pin.set_drive_strength(strength);
    }
    /// Transfer ownership without changing the pin's mode or output latch.
    /// Unlike ordinary Drop, this does not disconnect the pin.
    pub fn release(self) -> Peri<'d, AnyPin> {
        self.pin.release()
    }
}

/// GPIO open-drain output with input readback. Dropping it disconnects the pin.
pub struct OutputOpenDrain<'d> {
    pub(crate) pin: Flex<'d>,
}
impl<'d> OutputOpenDrain<'d> {
    pub fn new(
        pin: Peri<'d, impl Pin>,
        initial_output: Level,
        #[cfg(gpio_f030)] speed: Speed,
    ) -> Self {
        Self::new_pull(
            pin,
            initial_output,
            #[cfg(gpio_f030)]
            speed,
            Pull::None,
        )
    }
    /// Unsupported pull-downs panic before MMIO or latch changes.
    pub fn new_pull(
        pin: Peri<'d, impl Pin>,
        initial_output: Level,
        #[cfg(gpio_f030)] speed: Speed,
        pull: Pull,
    ) -> Self {
        let pin: Peri<'d, AnyPin> = pin.into();
        pin.validate_pull(pull);
        let mut pin = Flex::new(pin);
        pin.set_level(initial_output);
        pin.set_as_input_output_pull(
            #[cfg(gpio_f030)]
            speed,
            pull,
        );
        Self { pin }
    }
    pub fn is_high(&self) -> bool {
        self.pin.is_high()
    }
    pub fn is_low(&self) -> bool {
        self.pin.is_low()
    }
    pub fn level(&self) -> Level {
        self.pin.level()
    }
    pub fn set_high(&mut self) {
        self.pin.set_high();
    }
    pub fn set_low(&mut self) {
        self.pin.set_low();
    }
    pub fn set_level(&mut self, level: Level) {
        self.pin.set_level(level);
    }
    pub fn is_set_high(&self) -> bool {
        self.pin.is_set_high()
    }
    pub fn is_set_low(&self) -> bool {
        self.pin.is_set_low()
    }
    pub fn output_level(&self) -> Level {
        self.pin.output_level()
    }
    pub fn toggle(&mut self) {
        self.pin.toggle();
    }
    #[cfg(gpio_f030)]
    pub fn set_drive_strength(&mut self, strength: DriveStrength) {
        self.pin.set_drive_strength(strength);
    }
    /// Transfer ownership without changing the pin's mode or output latch.
    /// Unlike ordinary Drop, this does not disconnect the pin.
    pub fn release(self) -> Peri<'d, AnyPin> {
        self.pin.release()
    }
}

// embedded-hal also supplies the blanket &mut T implementations. Keep these
// infallible traits separate from the inherent bool/Level/() Embassy methods.
macro_rules! impl_error_type {
    ($($ty:ident),+ $(,)?) => { $(
        impl ErrorType for $ty<'_> { type Error = Infallible; }
    )+ };
}
macro_rules! impl_input_pin {
    ($($ty:ident),+ $(,)?) => { $(
        impl InputPin for $ty<'_> {
            fn is_high(&mut self) -> Result<bool, Self::Error> { Ok($ty::is_high(self)) }
            fn is_low(&mut self) -> Result<bool, Self::Error> { Ok($ty::is_low(self)) }
        }
    )+ };
}
macro_rules! impl_output_pin {
    ($($ty:ident),+ $(,)?) => { $(
        impl OutputPin for $ty<'_> {
            fn set_high(&mut self) -> Result<(), Self::Error> { $ty::set_high(self); Ok(()) }
            fn set_low(&mut self) -> Result<(), Self::Error> { $ty::set_low(self); Ok(()) }
        }
        impl StatefulOutputPin for $ty<'_> {
            fn is_set_high(&mut self) -> Result<bool, Self::Error> { Ok($ty::is_set_high(self)) }
            fn is_set_low(&mut self) -> Result<bool, Self::Error> { Ok($ty::is_set_low(self)) }
            fn toggle(&mut self) -> Result<(), Self::Error> { $ty::toggle(self); Ok(()) }
        }
    )+ };
}
impl_error_type!(Input, Output, OutputOpenDrain, Flex);
impl_input_pin!(Input, OutputOpenDrain, Flex);
impl_output_pin!(Output, OutputOpenDrain, Flex);

/// Sealed identity methods, implemented for generated pin tokens and AnyPin.
pub(crate) mod sealed {
    pub trait Pin {
        fn pin_port(&self) -> super::PinNumber;
    }
}
/// GPIO identity trait. MMIO configuration requires its exclusive Peri token.
#[allow(private_bounds)]
pub trait Pin: sealed::Pin + PeripheralType + Into<AnyPin> + Sized + 'static {
    /// Pin number within its port.
    fn pin(&self) -> PinNumber {
        self.pin_port() % 16
    }
    /// Port number: A = 0, B = 1, C = 2, F = 5.
    fn port(&self) -> PinNumber {
        self.pin_port() / 16
    }
}
impl PeripheralType for AnyPin {}
impl sealed::Pin for AnyPin {
    fn pin_port(&self) -> PinNumber {
        self.port.number() * 16 + self.number
    }
}
impl Pin for AnyPin {}
